# -*- coding: utf-8 -*-
"""ControlProcesos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Rou56Dr3xXrhfvhcqC31K1P7li_1_6aW
"""

pip install pyspc==0.4

import pandas as pd
from pyspc import *

import matplotlib.pyplot as plt

data = pd.read_csv('/content/GlobalTemperatures.csv')

# Initial shape
data.shape

data.head(5)

data = data.drop('dt', 1)
data = data.drop('LandAverageTemperatureUncertainty', 1)
data = data.drop('LandMaxTemperature', 1)
data = data.drop('LandMaxTemperatureUncertainty', 1)
data = data.drop('LandMinTemperature', 1)
data = data.drop('LandMinTemperatureUncertainty', 1)
data = data.drop('LandAndOceanAverageTemperature', 1)
data = data.drop('LandAndOceanAverageTemperatureUncertainty', 1)

data.head(5)

values = data[['LandAverageTemperature']].to_numpy()
one_d_array = values.ravel()
print('Dataset size: %d' % one_d_array.shape)
a = spc(one_d_array) + xmr() + rules()
print(a)